# Create a program that allows the user to enter data for a customer for the company "ABC Accounting".

# You will need to create the following classes, class variables, instance variables, constructors, and methods:

# Person class

    # Instance variables
        # name of type string (public)
        # address of type string (public)
        # city of type string (public)
        # state of type string (public)
        # zip of type string (public)

    # Constructor
        # receives parameters for all instance variables

# Customer class

# Inherits from Person class
    # Class variable called our_company with the value of "ABC Accounting"

    # Instance variables
        # num_employees of type int (public)
        # account of type Account (public)

    # Constructor
        # receives name, address, city, state, zip, and num_employees
        # calls super() in constructor and passes name, address, city, state, and zip to Person constructor
        # assigns the num_employees instance variable
        # creates the account object by calling Account
        # calls the account gen_account() method for the account object and passes the customer name and address as parameters

# Methods
    # print_customer() should return the customer info as BankingRUs with account Ban100 owes $150.00
        # where name is from the customer object
        # where account is from the account object
        # where balance is from the account object

# Account class

# Instance Variables
    # account_number of type string
# This will be generated by calling the gen_account() method
    # balance of type float
# Constructor
    # empty but you need to write it
# Methods
    # set_balance() receives balance and sets instance variable
    # gen_account() method receives the customer name and address to make the account value and stores to the instance variable account
    # The account will be the first 3 characters of the customer name and the first 3 characters from the address

# Name: Toa Pita
# Section: 003
# Project Description: This program allows the user to enter information for different customers. It then displays the processed information.

# Creating a Person Class
class Person():
    # Creating the constructor and initializing the attributes using passed in parameters
    def __init__(self,name,address,city,state,zip):
        self.name = name # String
        self.address = address # String
        self.city = city # String
        self.state = state # String
        self.zip = zip # String

# Creating a customer class that extends Person
class Customer(Person):
    # Class variable so the name stays the same across all customers
    our_company = "ABC Accounting"
    # Another constructor that also calls the parent constructor. Also creates an new instance of Account.
    def __init__(self, name, address, city, state, zip, num_employees):
        super().__init__(name, address, city, state, zip)
        self.num_employees = num_employees #type int
        self.account = Account() #type account
        self.account.gen_account(self.name,self.address)
    # Create a way to output info
    def print_customer(self):
        output = self.name + " with account "+ self.account.account_number + " owes "+"${:,.2f}".format(self.account.balance)
        return output

    # getter for account
    def get_account(self):
        return self.account

# Create an account class
class Account():
    # Intialize instance variables
    def __init__(self):
        self.account_number = ""
        self.balance = 0.0

    # Generate the account using the first 3 chars of name and the first 3 chars of address
    def gen_account(self,name,address):
        self.account_number = name[0:3] + address[0:3]
        
    # A setter for balance
    def set_balance(self,balance):
        self.balance = balance #Float





